### ISSUE TITLE
ultima versione 0.2.1 in QGIS 2.18.12 - selectChildFromParent non funziona sempre

### ISSUE THREAD

**Issue by pigreco** [pyarchinit/selectbyrelationship_repo#10]
@slarosa , @pyarchinit 
Definita la relazione nel progetto, layer padre vettore, layer figlio semplice tabella;
se il vettore (padre) non ha figli, NON è possibile selezionare il record nè da map canvas nè dalla tabella attributi.

**Comment by slarosa** [comment]
@pigreco test per conferma sono benvenuti :-)
