### ISSUE TITLE
owners errato!!!

### ISSUE THREAD

**Issue by pigreco** [pyarchinit/selectbyrelationship_repo#11]
@slarosa @pyarchinit 
![image](https://user-images.githubusercontent.com/7631137/31669663-fb7b756c-b355-11e7-8781-dc25d213138c.png)

https://plugins.qgis.org/plugins/SelectByRelationship/

**Comment by slarosa** [comment]
Purtroppo non è un problema del plugin, dipende dalla piattaforma web che gestisce il caricamento dei plugins. Meglio se apri la segnalazione qui: [qgis/QGIS-Django](https://github.com/qgis/QGIS-Django/issues)

**Comment by pigreco** [comment]
Ho chiesto a @pyarchinit (Luca) di aprire una segnalazione!!!
Thx

**Comment by pyarchinit** [comment]
Ticket aperto: https://github.com/qgis/QGIS-Django/issues/53

**Comment by pigreco** [comment]
sembra sistemato:
![image](https://user-images.githubusercontent.com/7631137/31715127-e504581e-b402-11e7-9699-762b628f6d6a.png)

**Comment by slarosa** [comment]
bene, sto chiudendo!
