### ISSUE TITLE
Issue with the settings svg file

### ISSUE THREAD

**Issue by DelazJ** [pyarchinit/selectbyrelationship_repo#16]
Hi,
With this plugin installed, i often get in the message bar
```CRITICAL    Qt : C:\Users\pclocal\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\SelectByRelationship\images\settings.svg:1:6337: Could not resolve property: i```
Afaics, it does not break anything in the process but wanted to report.

Using version 0.3.0 with QGIS 3.8 and 3.9

**Comment by slarosa** [comment]
Thank you @DelazJ, svgcleaner has solved it.
