### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by dmonterr** [pyarchinit/selectbyrelationship_repo#19]
The plugin is not working corectly in the new version of QGIS  (3.12.3). I try to reinstall it, but it didnt  work.

Edit:
It only works if relationship "Name" and "Id" are the same.

Thanks for this amazing plugin btw!

**Comment by pigreco** [comment]
duplicate #17

**Comment by slarosa** [comment]
fixed in 99c5d656202d1b3794752b8337b32c11f81fada9
