### ISSUE TITLE
selezionare in entrambe i sensi con zoom alla selezione

### ISSUE THREAD

**Issue by pigreco** [pyarchinit/selectbyrelationship_repo#2]
sarebbe utile poter fare anche:

1. **lo zoom alla selezione**; nella tabella padre è gia possibile in quanto ha la geometria, ma nella tabella correlata, che non ha geometria, sarebbe molto utile poter zoomare alla geometria padre;
2. **la selezione in entrambi i lati della relazione 1:M**; per adesso è possibile solo selezionare la feature padre partendo dalla tabella figlio, sarebbe utile anche fare al contrario, selezionare una feature (padre) ed avere selezionati le righe della tabella figlia;

**Comment by ghost** [comment]
Hi Luca,
I think is better, if in this repo, you add  a sample project (.qgs) with 2 layers and a relation 1:M !!
Bye
Nino

**Comment by pyarchinit** [comment]
That's a good idea!
