### ISSUE TITLE
Please remove the zipfile

### ISSUE THREAD

**Issue by pcav** [pyarchinit/selectbyrelationship_repo#6]
It does not belong here.
Also .gitignore shouldn't be there. Please follow structure as seen in other plugins.
Thanks.

**Comment by pyarchinit** [comment]
zip file and gitignore deleted.

**Comment by slarosa** [comment]
@pcav what is the problem with .gitignore file? and how it is related to the release process for plugin?

**Comment by pcav** [comment]
We try to ensure the code is clean.
Thanks.

**Comment by slarosa** [comment]
@pcav wrote:
> We try to ensure the code is clean.

exactly what gitignore does :-)

**Comment by pcav** [comment]
Not

**Comment by slarosa** [comment]
@pcav sorry for the question but it could be useful if you can explain the reason better. Should we permanently delete the file? I see others plugin repository where the file is there.
