### ISSUE TITLE
ultima versione 0.2.1 in QGIS 2.18.10 - map canvas si blocca

### ISSUE THREAD

**Issue by pigreco** [pyarchinit/selectbyrelationship_repo#9]
Ciao, @slarosa e @pyarchinit 
ho appena scoperto che se il layer, lato 1 (nella relazione), è una semplice tabella senza geometria, la map canvas si blocca (senza nessun messaggio di errore) e non permette più di lavorare.
Ho attivato tutte le funzionalità, in particolare riga 201, 202 e 203.

![image](https://user-images.githubusercontent.com/7631137/28325744-efaaa834-6bde-11e7-9e9c-64ac4b33cf66.png)

il problema credo sia legato alla riga 201 dove fa lo zoomParentFeature, ma non tovando geometria si blocca tutto.

**Comment by slarosa** [comment]
@pigreco layer 1 significa Layer padre? puoi allegare un progetto esempio?
Grazie!

**Comment by slarosa** [comment]
puoi allegarlo anche qui https://github.com/pigreco/test_plugin_selectbyrelationship :-)

**Comment by pigreco** [comment]
@slarosa @pyarchinit 
[qui](https://github.com/pigreco/test_plugin_selectbyrelationship/blob/master/test_r.7z) trovi il progetto e i dati.
Ho un layer padre (CSV) e un figlio (shp), ho creato relazione.
Selezionando un record, in tabella attributi aperta, si blocca tutto!!!

**Comment by pigreco** [comment]
@slarosa @pyarchinit 
aggiungo video demo:
https://youtu.be/1H6tJESvIWM

**Comment by slarosa** [comment]
@pigreco test per conferma sono benvenuti :-)

**Comment by pigreco** [comment]
@slarosa 
appena finito di fare test!!!
tutto perfetto!!!
grazie!!!

**Comment by slarosa** [comment]
grazie a te Totò!
